const LOGIN_SAGA = "LOGIN_SAGA";
const USER_DATA_STORE = 'USER_DATA_STORE';
const SEARCH_PRODUCTS_SAGA = "SEARCH_PRODUCTS_SAGA";
const SEARCH_PRODUCTS_STORE = "SEARCH_PRODUCTS_STORE";
const PRODUCT_SAGA = 'PRODUCT_SAGA';
const PRODUCT_STORE = 'PRODUCT_STORE';


export {LOGIN_SAGA ,USER_DATA_STORE,SEARCH_PRODUCTS_SAGA,SEARCH_PRODUCTS_STORE ,PRODUCT_SAGA ,PRODUCT_STORE}